### ISSUE TITLE
GitHub Issue で TODO の進捗率が表示されるパターン、されないパターンを調べる

### ISSUE THREAD

**Issue by shouh** [shouh/test_repo#60]
* [ ] body todo 1
* [ ] body todo 2
* [ ] body todo 3

ちょっと離して。

* [ ] body todo separeted 1
* [ ] body todo separeted 2

サブもつけてみようか。

* [ ] body todo nested 1
  * [ ] body todo nested 1-1
    * [x] body todo nested 1-1-1
      * [x] body todo nested 1-1-1-1
        * [x] body todo nested 1-1-1-1-1

**Comment by shouh** [comment]
* [ ] issue comment todo 1
* [ ] issue comment todo 2
* [ ] issue comment todo 3

ちょっと離して。

* [ ] issue comment todo separated 1
* [ ] issue comment todo separated 2
